version: '3'

services:
  db-mysql:
    image: mysql:5.7
    container_name: db-mysql
    restart: always
    tty: true
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=joao
      - MYSQL_USER=joao
    networks:
      - nodenet

  nodejs:
    build:
      context: node
    container_name: nodejs
    entrypoint: dockerize -wait tcp://db-mysql:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - nodenet
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db-mysql

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    networks:
      - nodenet
    tty: true
    ports:
      - "8080:80"
      
networks:
  nodenet:
    driver: bridge